### ISSUE TITLE
Problem with running gulp for building the app

### ISSUE THREAD

**Issue by nguyenthong** [rlafranchi/foundation-apps-rails#1]
Hi

I was on your branch post and try to run gulp to build the project but the new foundation.js script doesn't work as it was expected.

**Comment by rlafranchi** [comment]
Try running gulp now.  The directory structure for foundation for apps changed a bit.  I updated the master, but forgot to include in the posts branch.  Let me know if it works for you.

**Comment by nguyenthong** [comment]
Hi, thank you so much. It is working now.
