### ISSUE TITLE
branch posts is not working for me 

### ISSUE THREAD

**Issue by unplugandplay** [rlafranchi/foundation-apps-rails#2]
I have the following problems in firebug :  

Error: [$injector:modulerr] Failed to instantiate module app due to:
[$injector:modulerr] Failed to instantiate module application.services due to:
[$injector:modulerr] Failed to instantiate module platanus.inflector due to:
[$injector:nomod] Module 'platanus.inflector' is not available! 

Can you help me

**Comment by rlafranchi** [comment]
Try running `bower install` from the root directory and run `gulp` again when you are on the posts branch.  The posts branch includes a dependency for angular-inflector which is not included in master.  This should solve the problem.

**Comment by unplugandplay** [comment]
thanks !
