### ISSUE TITLE
Creating your own scss files

### ISSUE THREAD

**Issue by steltz** [rlafranchi/foundation-apps-rails#4]
Hi Richard! First off, thank you for this scaffold, its an awesome starting point. 

I can't figure out how to get my custom scss files into the asset pipeline. I've never used gulp, and I'm not sure how the stylesheet assets are being compiled. Could you give me any pointers?

**Comment by natematykiewicz** [comment]
I'm not sure how familiar you are with a Rails app. The routes file and application layout file tell you a lot about this setup.

The [application.html.erb](https://github.com/rlafranchi/foundation-apps-rails/blob/master/app/views/layouts/application.html.erb) file shows that only one scss file is being included:

``` ruby
<%= stylesheet_link_tag    'application', media: 'all' %>
```

That scss file can be found in:
https://github.com/rlafranchi/foundation-apps-rails/blob/master/app/assets/stylesheets/application.scss

It's a standard Rails asset pipeline, so you'll want to make .scss files under `app/assets/stylesheets`, and then add `@import` lines to the `application.scss` files for your custom files.

This page gives more info on the Rails asset pipeline
http://guides.rubyonrails.org/asset_pipeline.html#manifest-files-and-directives

If you have any other questions, I can try to help. I'm a Rails dev that's very new to Angular. So, I understand the Rails half of all of this, but am learning how Angular works.

**Comment by steltz** [comment]
Thanks Nate! I've tried that setup and it wasn't working, I'll try again tonight.

**Comment by natematykiewicz** [comment]
Strange. I had tried it out before I posted.

I'm not sure what you're doing to test it, so I don't know if you are expecting to see another css `<link>` tag in the HTML or something.

All of the scss files get concatenated into a single "applications" css file (mine's current name is `application.self-d056fa81eece4954ae160c67172461b3af9b439887b61b7c115adcd8884295f2.css`) in the order that it's in in the application.scss file. Try adding `body { background: red !important; }` to a custom scss file (that you've imported into application.scss) and see if the background turns red. If it does, your css is in there somewhere!

What are you doing to test whether it works or not?

**Comment by rlafranchi** [comment]
@steltz, Thanks for the interest.  It's been a while since I've looked at this repo, so it's possible there are bugs related to outdated dependencies and may not be completely compatible with the current version of foundation for apps.

As @natematykiewicz stated:

>  It's a standard Rails asset pipeline, so you'll want to make .scss files under app/assets/stylesheets, and then add `@import` lines to the `application.scss` files for your custom files.

Example, given you have a custom scss file at `app/assets/stylesheets/custom.scss`:
add `@import "custom";` to the `application.scss` file

Also, the `_settings.scss` file includes the foundation variables which can be modified appropriately.

Let me know if that helps.

**Comment by steltz** [comment]
@natematykiewicz @rlafranchi  I really appreciate your help, thank you.

I still can't figure out why this isn't working...

<img width="1034" alt="screen shot 2016-02-27 at 1 57 31 pm" src="https://cloud.githubusercontent.com/assets/11165316/13374703/657c0fae-dd5a-11e5-97a5-adf3a568b1ea.png">

I'll google around to see if I can't figure it out.

**Comment by natematykiewicz** [comment]
Can you paste in the contents of the `<head>` tag that's being generated when you visit your app? I'd like to get an understanding of how your assets are being loaded in.

Also, what version of Rails are you using? I did jump straight to upgrading Rails to 4.2.5.1 before doing anything. I don't think that would make much of a difference, though.

**Comment by steltz** [comment]
I think I may have figured it out, I've never used scss in Sublime Text before so my custom.scss file is currently a plain text file. This would explain why the file isn't getting loaded in...

**Comment by steltz** [comment]
Here is the head tag:

<img width="1133" alt="screen shot 2016-02-27 at 2 17 15 pm" src="https://cloud.githubusercontent.com/assets/11165316/13374813/47e6470e-dd5d-11e5-8b93-bbd2b552bf70.png">

**Comment by steltz** [comment]
<img width="994" alt="screen shot 2016-02-27 at 2 25 03 pm" src="https://cloud.githubusercontent.com/assets/11165316/13374839/f6341dcc-dd5d-11e5-8377-d07264abbda3.png">

**Comment by steltz** [comment]
I ran bundle update rails, and I'm using 4.2.0

**Comment by natematykiewicz** [comment]
Rails reads a .scss file and builds a .css file out of it. So, that's expected.

Those @import lines are going to add the content of other scss files, into the css file that's built. They're added in the order that you specify them. If any of Foundation is setting the background on `body`, then it could be overriding your style. I would put Foundation first, and then any of your style after Foundations. This will give you the best chance of overriding style.

Importing files into each other will speed up page loads. This is why all of the content is being put into 1 file. Downloading 1 file is a lot faster than downloading 10, even if the total file size adds up to be the same.

It may be good to edit `config/environments/development.rb` and set `config.assets.digest = true`. This will change the filename of your output CSS every time it's update (adding the MD5 of the file's contents to the filename), which will prevent the browser from caching old versions of CSS files on you. Either that, or disable caching in Chrome while you develop, so the cache doesn't fight you.

You might want to read up on the Rails asset pipeline a bit. http://guides.rubyonrails.org/asset_pipeline.html

**Comment by steltz** [comment]
Sounds good, thank you Nate! I appreciate you taking the time to respond to my questions.

**Comment by natematykiewicz** [comment]
Running `bundle update rails` won't update it on its own. You'll need to edit your Gemfile to lock to the correct version you want. (It's common practice to define an EXACT version of Rails in the Gemfile, because updating Rails version is a big deal to an app.)

`gem 'rails', '4.2.5.1'` would be the current version.
After your Gemfile has been updated, run `bundle update rails`. Now your Gemfile.lock will be updated.

http://bundler.io will teach you about how Bundler works. Feel free to ask questions, though.

Two very important things to know about Bundler:
- Only make changes to the Gemfile
- Never touch the Gemfile.lock (Bundler will generate it for you)

**Comment by rlafranchi** [comment]
Agreed that the order in which files are loaded is important, so be sure to import custom files after foundation is imported.  Also, I try to look for an appropriate foundation variable for customizing before writing my own: i.e. `$body-background: #efefef;`

Closing...  I'm not actively maintaining this project, so if either of you see room for improvements, feel free to create a pull request.
